version: 2
registries:
  fp-felles:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-felles
    username: x-access-token
    password: ${{secrets.GH_ACCESS_TOKEN}} 
  fp-prosesstask:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-prosesstask
    username: x-access-token
    password: ${{secrets.GH_ACCESS_TOKEN}} 
  fp-kontrakter:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-kontrakter
    username: x-access-token
    password: ${{secrets.GH_ACCESS_TOKEN}}
  fp-tidsserie:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/fp-tidsserie
    username: x-access-token
    password: ${{secrets.GH_ACCESS_TOKEN}}
  tjenestespesifikasjoner:
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/tjenestespesifikasjoner
    username: x-access-token
    password: ${{secrets.GH_ACCESS_TOKEN}} 
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    registries:
      - fp-felles
      - fp-prosesstask
      - fp-tidsserie
      - tjenestespesifikasjoner
      - fp-kontrakter
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
