kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: fpabakus
  namespace: q1
  labels:
    team: teamforeldrepenger
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://fpabakus-q1.nais.preprod.local/"
  liveness:
    path: "/fpabakus/internal/isAlive"
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: "/fpabakus/internal/isReady"
    initialDelay: 30
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: "/fpabakus/internal/metrics/prometheus"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  preStopHookPath: "/fpabakus/internal/preStop"
  resources:
    limits:
      cpu: "2000m"
      memory: "2048Mi"
    requests:
      cpu: "600m"
      memory: "1024Mi"
  vault:
    enabled: true
    sidecar: false
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: serviceuser/data/dev/srvfpabakus
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/preprod/fss/fpabakus/q1
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev
  env:
    - name: LOADBALANCER_URL
      value: https://fpabakus-q1.nais.preprod.local
    - name: ABAC_PDP_ENDPOINT_URL
      value: https://wasapp-q1.adeo.no/asm-pdp/authorize
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    #OpenID
    - name: OPENIDCONNECT_ISSOHOST
      value: https://isso-q.adeo.no:443/isso/oauth2
    - name: OPENIDCONNECT_ISSOISSUER
      value: https://isso-q.adeo.no:443/isso/oauth2
    - name: OPENIDCONNECT_ISSOJWKS
      value: https://isso-q.adeo.no:443/isso/oauth2/connect/jwk_uri
    #OIDC
    - name: OIDC_STS_ISSUERURL
      value: https://security-token-service.nais.preprod.local
    - name: OIDC_STS_JWKSURL
      value: https://security-token-service.nais.preprod.local/rest/v1/sts/jwks
    #Generell Kafka
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-test-schema-registry.nais.preprod.local
    #Eksterne systemer
    - name: HENTINNTEKTLISTEBOLK_URL
      value: https://app-q1.adeo.no/inntektskomponenten-ws/rs/api/v1/hentinntektlistebolk
    - name: ARBEIDSFORHOLD_V3_URL
      value: https://modapp-q1.adeo.no/aareg-services/ArbeidsforholdService/v3
    - name: MELDEKORTUTBETALINGSGRUNNLAG_V1_URL
      value: https://arena-q1.adeo.no/ail_ws/MeldekortUtbetalingsgrunnlag_v1
    - name: AKTOER_V2_URL
      value: https://app-q1.adeo.no/aktoerregister/ws/Aktoer/v2
    - name: PERSON_V3_URL
      value: https://wasapp-q1.adeo.no/tpsws/ws/Person/v3
    - name: SIGRUNRESTBEREGNETSKATT_URL
      value: https://sigrun-q1.nais.preprod.local
    - name: ORGANISASJON_V4_URL
      value: https://modapp-q1.adeo.no/ereg/ws/OrganisasjonService/v4
    - name: FPABAKUS_IT_FP_GRUNNLAG_URL
      value: http://infotrygd-foreldrepenger.default/grunnlag
    - name: FPABAKUS_IT_SVP_GRUNNLAG_URL
      value: http://infotrygd-svangerskapspenger.default/grunnlag
    - name: FPABAKUS_IT_PS_GRUNNLAG_URL
      value: http://infotrygd-grunnlag-paaroerende-sykdom.default/paaroerendeSykdom/grunnlag
    - name: FPABAKUS_IT_SP_GRUNNLAG_URL
      value: http://infotrygd-sykepenger-fp.default/grunnlag
