kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: fpabakus
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://fpabakus.nais.preprod.local"
    - "https://fpabakus.dev.adeo.no"
    - "https://fpabakus.dev.intern.nav.no"
    - "https://fpabakus.dev-fss-pub.nais.io"
  liveness:
    path: "/fpabakus/internal/isAlive"
    initialDelay: 25
    timeout: 5
    periodSeconds: 7
    failureThreshold: 27
  readiness:
    path: "/fpabakus/internal/isReady"
    initialDelay: 25
    timeout: 5
    periodSeconds: 7
    failureThreshold: 27
  prometheus:
    enabled: true
    path: "/fpabakus/internal/metrics/prometheus"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  preStopHookPath: "/fpabakus/internal/preStop"
  resources:
    limits:
      cpu: "2000m"
      memory: "2048Mi"
    requests:
      cpu: "1200m"
      memory: "1024Mi"
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        extra:
          - "NAVident"
          - "azp_name"
  accessPolicy:
      inbound:
        rules:
          - application: fp-swagger
            namespace: teamforeldrepenger
            cluster: dev-gcp
            permissions:
              scopes:
                - "swagger"
          - application: fpsak
            namespace: teamforeldrepenger
            cluster: dev-fss
          - application: k9-sak
            namespace: k9saksbehandling
            cluster: dev-fss
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: serviceuser/data/dev/srvfpabakus
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev
  env:
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    #OpenAM
    - name: OIDC_OPEN_AM_WELL_KNOWN_URL
      value: https://isso-q.adeo.no:443/isso/oauth2/.well-known/openid-configuration
    #STS
    - name: OIDC_STS_WELL_KNOWN_URL
      value: https://security-token-service.nais.preprod.local/.well-known/openid-configuration
    #ABAC
    - name: ABAC_ATTRIBUTT_DRIFT
      value: "no.nav.abac.attributter.resource.duplo.abakus.drift"
    #Generell Kafka
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-test-schema-registry.nais.preprod.local
    - name: KAFKA_FATTEVEDTAK_TOPIC
      value: privat-familie-vedtakFattet-v1-q1
    #Eksterne systemer
    - name: HENTINNTEKTLISTEBOLK_URL
      value: https://app-q1.adeo.no/inntektskomponenten-ws/rs/api/v1/hentinntektlistebolk
    - name: AAREG_RS_URL
      value: http://aareg-services-nais-q1.arbeidsforhold/api/v1/arbeidstaker
    - name: MELDEKORTUTBETALINGSGRUNNLAG_V1_URL
      value: https://arena-q1.adeo.no/ail_ws/MeldekortUtbetalingsgrunnlag_v1
    - name: SIGRUNRESTBEREGNETSKATT_URL
      value: https://sigrun-q1.dev.adeo.no
    - name: ORGANISASJON_RS_URL
      value: https://modapp-q1.adeo.no/ereg/api/v1/organisasjon
    - name: FPABAKUS_IT_FP_GRUNNLAG_URL
      value: http://infotrygd-foreldrepenger.default/grunnlag
    - name: FPABAKUS_IT_PS_GRUNNLAG_URL
      value: http://k9-infotrygd-grunnlag-paaroerende-sykdom.k9saksbehandling/paaroerendeSykdom/grunnlag
    - name: FPABAKUS_IT_SP_GRUNNLAG_URL
      value: http://infotrygd-sykepenger-fp.default/grunnlag
    #AZURE
    - name: AZURE_HTTP_PROXY
      value: http://webproxy.nais:8088
    #SPOKELSE
    - name: SPOKELSE_GRUNNLAG_SCOPES
      value: api://dev-fss.tbd.spokelse/.default
    - name: SPOKELSE_GRUNNLAG_URL
      value: http://spokelse.tbd/grunnlag

    - name: SKAL_INNENTE_YTELSE_ANVIST_ANDELER
      value: "true"
    - name: APPD_ENABLED
      value: "false"
