kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: fpabakus
  namespace: default
  labels:
    team: teamforeldrepenger
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://fpabakus.nais.preprod.local/"
    - "https://fpabakus.dev.adeo.no/"
  liveness:
    path: "/fpabakus/internal/isAlive"
    initialDelay: 25
    timeout: 5
    periodSeconds: 7
    failureThreshold: 27
  readiness:
    path: "/fpabakus/internal/isReady"
    initialDelay: 25
    timeout: 5
    periodSeconds: 7
    failureThreshold: 27
  prometheus:
    enabled: true
    path: "/fpabakus/internal/metrics/prometheus"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 80
  preStopHookPath: "/fpabakus/internal/preStop"
  resources:
    limits:
      cpu: "2000m"
      memory: "2048Mi"
    requests:
      cpu: "600m"
      memory: "1024Mi"
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: serviceuser/data/dev/srvfpabakus
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/dev
      - mountPath: /var/run/secrets/nais.io/azuread
        kvPath: /azuread/data/dev/creds/fp-abakus
  env:
    - name: LOADBALANCER_URL
      value: https://fpabakus.nais.preprod.local
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-duplo.default/application/authorize
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts-q1.preprod.local/SecurityTokenServiceProvider/
    #OpenID
    - name: OPENIDCONNECT_ISSOHOST
      value: https://isso-q.adeo.no:443/isso/oauth2
    - name: OPENIDCONNECT_ISSOISSUER
      value: https://isso-q.adeo.no:443/isso/oauth2
    - name: OPENIDCONNECT_ISSOJWKS
      value: https://isso-q.adeo.no:443/isso/oauth2/connect/jwk_uri
    #OIDC
    - name: OIDC_STS_ISSUER_URL
      value: https://security-token-service.nais.preprod.local
    - name: OIDC_STS_JWKS_URL
      value: http://security-token-service.default/rest/v1/sts/jwks
    #ABAC
    - name: ABAC_ATTRIBUTT_DRIFT
      value: "no.nav.abac.attributter.resource.duplo.abakus.drift"
    #Sensu
    - name: SENSU_HOST
      value: sensu.nais
    - name: SENSU_PORT
      value: "3030"
    #Generell Kafka
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: b27apvl00045.preprod.local:8443,b27apvl00046.preprod.local:8443,b27apvl00047.preprod.local:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: https://kafka-test-schema-registry.nais.preprod.local
    - name: KAFKA_FATTEVEDTAK_TOPIC
      value: privat-familie-vedtakFattet-v1-q1
    - name: KAFKA_LONNSKOMPENSASJON_TOPIC
      value: privat-permittering-lonnskomp-vedtak
    #Eksterne systemer
    - name: HENTINNTEKTLISTEBOLK_URL
      value: https://app-q1.adeo.no/inntektskomponenten-ws/rs/api/v1/hentinntektlistebolk
    - name: AAREG_RS_URL
      value: https://modapp-q1.adeo.no/aareg-services/api/v1/arbeidstaker
    - name: MELDEKORTUTBETALINGSGRUNNLAG_V1_URL
      value: https://arena-q1.adeo.no/ail_ws/MeldekortUtbetalingsgrunnlag_v1
    - name: SIGRUNRESTBEREGNETSKATT_URL
      value: https://sigrun-q1.nais.preprod.local
    - name: ORGANISASJON_RS_URL
      value: https://modapp-q1.adeo.no/ereg/api/v1/organisasjon
    - name: FPABAKUS_IT_FP_GRUNNLAG_URL
      value: http://infotrygd-foreldrepenger.default/grunnlag
    - name: FPABAKUS_IT_PS_GRUNNLAG_URL
      value: http://infotrygd-grunnlag-paaroerende-sykdom.default/paaroerendeSykdom/grunnlag
    - name: FPABAKUS_IT_SP_GRUNNLAG_URL
      value: http://infotrygd-sykepenger-fp.default/grunnlag
    #AZURE
    - name: AZURE_V2_TOKEN_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/oauth2/v2.0/token
    - name: AZURE_HTTP_PROXY
      value: http://webproxy.nais:8088
    #SPOKELSE
    - name: SPOKELSE_GRUNNLAG_SCOPES
      value: 60c763a5-2b52-4d0f-b080-0effbf75de2e/.default
    # Graphql services
    - name: SAF_BASE_URL
      value: http://saf.q1
