kind: "Application"
apiVersion: "nais.io/v1alpha1"
metadata:
  name: fpabakus
  namespace: teamforeldrepenger
  labels:
    team: teamforeldrepenger
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://fpabakus.nais.adeo.no/"
  liveness:
    path: "/fpabakus/internal/isAlive"
    initialDelay: 25
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  readiness:
    path: "/fpabakus/internal/isReady"
    initialDelay: 25
    timeout: 5
    periodSeconds: 10
    failureThreshold: 27
  prometheus:
    enabled: true
    path: "/fpabakus/internal/metrics/prometheus"
  replicas:
    min: 4
    max: 6
    cpuThresholdPercentage: 80
  preStopHookPath: "/fpabakus/internal/preStop"
  resources:
    limits:
      cpu: "2000m"
      memory: "2048Mi"
    requests:
      cpu: "600m"
      memory: "1024Mi"
  secureLogs:
    enabled: true
  azure:
    application:
      enabled: true
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: serviceuser/data/prod/srvfpabakus
      - mountPath: /var/run/secrets/nais.io/vault
        kvPath: /kv/prod/fss/fpabakus/teamforeldrepenger
      - mountPath: /var/run/secrets/nais.io/appdynamics
        kvPath: /apikey/appdynamics/prod
  env:
    - name: LOADBALANCER_URL
      value: https://fpabakus.nais.adeo.no
    - name: ABAC_PDP_ENDPOINT_URL
      value: http://abac-duplo.teamabac/application/authorize
    - name: SECURITYTOKENSERVICE_URL
      value: https://sts.adeo.no/SecurityTokenServiceProvider/
    #OpenID
    - name: OIDC_OPEN_AM_WELL_KNOWN_URL
      value: https://isso.adeo.no:443/isso/oauth2/.well-known/openid-configuration
    - name: OPENIDCONNECT_ISSOHOST
      value: https://isso.adeo.no:443/isso/oauth2
    #OIDC
    - name: OIDC_STS_WELL_KNOWN_URL
      value: https://security-token-service.nais.adeo.no/.well-known/openid-configuration
    #ABAC
    - name: ABAC_ATTRIBUTT_DRIFT
      value: "no.nav.abac.attributter.resource.duplo.abakus.drift"
    #Generell Kafka
    - name: KAFKA_BOOTSTRAP_SERVERS
      value: a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: KAFKA_SCHEMA_REGISTRY_URL
      value: http://kafka-schema-registry.tpa:8081
    - name: KAFKA_FATTEVEDTAK_TOPIC
      value: privat-familie-vedtakFattet-v1
    # Eksterne systemer
    - name: PDL_BASE_URL
      value: http://pdl-api.pdl/graphql
    - name: HENTINNTEKTLISTEBOLK_URL
      value: https://app.adeo.no/inntektskomponenten-ws/rs/api/v1/hentinntektlistebolk
    - name: AAREG_RS_URL
      value: https://modapp.adeo.no/aareg-services/api/v1/arbeidstaker
    - name: MELDEKORTUTBETALINGSGRUNNLAG_V1_URL
      value: https://arena.adeo.no/ail_ws/MeldekortUtbetalingsgrunnlag_v1
    - name: SIGRUNRESTBEREGNETSKATT_URL
      value: https://sigrun.nais.adeo.no
    - name: ORGANISASJON_RS_URL
      value: https://modapp.adeo.no/ereg/api/v1/organisasjon
    - name: FPABAKUS_IT_FP_GRUNNLAG_URL
      value: http://infotrygd-foreldrepenger.default/grunnlag
    - name: FPABAKUS_IT_PS_GRUNNLAG_URL
      value: http://k9-infotrygd-grunnlag-paaroerende-sykdom.k9saksbehandling/paaroerendeSykdom/grunnlag
    - name: FPABAKUS_IT_SP_GRUNNLAG_URL
      value: http://infotrygd-sykepenger-fp.default/grunnlag
    #AZURE
    - name: AZURE_HTTP_PROXY
      value: http://webproxy.nais:8088
    #SPOKELSE
    - name: SPOKELSE_GRUNNLAG_SCOPES
      value: api://prod-fss.tbd.spokelse/.default
    - name: SPOKELSE_GRUNNLAG_URL
      value: http://spokelse.tbd/grunnlag

    - name: SKAL_INNENTE_YTELSE_ANVIST_ANDELER
      value: "true"
