drop index IDX_KONFIG_VERDI_KODE_1;
drop index IDX_KONFIG_VERDI_KODE_2;
drop INDEX IDX_KONFIG_VERDI_1;
drop INDEX IDX_KONFIG_VERDI_3;
drop INDEX IDX_KONFIG_VERDI_2;
drop INDEX UIDX_KONFIG_VERDI_1;

drop TABLE KONFIG_VERDI_KODE CASCADE ;
drop TABLE KONFIG_VERDI cascade ;

drop sequence seq_konfig_verdi;
