INSERT INTO KODEVERK (kode, navn, beskrivelse, kodeverk_eier)
VALUES ('TEMA_UNDERKATEGORI', 'Kodeverk for tema underkategori i ytelse', 'Kodeverk for tema underkategori i ytelse','VL');

INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'FØ','Foreldrepenger fødsel','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'AP','Foreldrepenger adopsjon','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'SV','Svangerskapspenger','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'AE','Adopsjon engangsstønad','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'FE','Fødsel engangsstønad','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'FU','Foreldrepenger fødsel, utland','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'RS','Forsikr.risiko sykefravær','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'RT','Reisetilskudd','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'SP','Sykepenger','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'SU','Sykepenger utenlandsopphold','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'BT','Stønad til barnetilsyn','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'FL','Tilskudd til flytting','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'OG','Overgangsstønad','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'UT','Skolepenger','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));

INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'OM','Pårørende omsorgsmpenger','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'OP','Pårørende opplæringspenger','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'PB','Pårørende pleietrengende sykt barn','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'PI','Pårørende pleietrengende','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'PP','Pårørende pleietrengende pårørende','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', 'PN','Pårørende pleiepenger','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));

INSERT INTO KODELISTE (ID, KODEVERK, KODE, NAVN, BESKRIVELSE, SPRAK, GYLDIG_FOM, GYLDIG_TOM) VALUES (nextval('SEQ_KODELISTE') ,'TEMA_UNDERKATEGORI', '-','Udefinert','','NB', to_date('01.01.2000', 'dd.mm.yyyy'), to_date('31.12.9999', 'dd.mm.yyyy'));
