INSERT INTO KODEVERK (KODE, KODEVERK_EIER, KODEVERK_EIER_REF, KODEVERK_EIER_VER, KODEVERK_EIER_NAVN,
                      KODEVERK_SYNK_NYE, KODEVERK_SYNK_EKSISTERENDE, NAVN, BESKRIVELSE, SAMMENSATT)
VALUES ('LANDKODER', 'Kodeverkforvaltning', 'http://nav.no/kodeverk/Kodeverk/Landkoder', '1', 'Landkoder',
        'J', 'J', 'Landkoder', 'NAV kopi av ISO 3166-1-alpha-3 3-bokstav landkoder', 'N');
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', '???', '???', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', '349', '349', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', '546', '546', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', '556', '556', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', '669', '669', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ABW', 'ABW', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'AFG', 'AFG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'AGO', 'AGO', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'AIA', 'AIA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ALA', 'ALA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ALB', 'ALB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'AND', 'AND', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ANT', 'ANT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ARE', 'ARE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ARG', 'ARG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ARM', 'ARM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ASM', 'ASM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ATF', 'ATF', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ATG', 'ATG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'AUS', 'AUS', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'AUT', 'AUT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'AZE', 'AZE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BDI', 'BDI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BEL', 'BEL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BEN', 'BEN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BES', 'BES', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BFA', 'BFA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BGD', 'BGD', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BGR', 'BGR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BHR', 'BHR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BHS', 'BHS', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BIH', 'BIH', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BLM', 'BLM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BLR', 'BLR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BLZ', 'BLZ', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BMU', 'BMU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BOL', 'BOL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BRA', 'BRA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BRB', 'BRB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BRN', 'BRN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BTN', 'BTN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BVT', 'BVT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'BWA', 'BWA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CAF', 'CAF', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CAN', 'CAN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CCK', 'CCK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CHE', 'CHE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CHL', 'CHL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CHN', 'CHN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CIV', 'CIV', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CMR', 'CMR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'COD', 'COD', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'COG', 'COG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'COK', 'COK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'COL', 'COL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'COM', 'COM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CPV', 'CPV', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CRI', 'CRI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CSK', 'CSK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CUB', 'CUB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CUW', 'CUW', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CXR', 'CXR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CYM', 'CYM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CYP', 'CYP', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'CZE', 'CZE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'DDR', 'DDR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'DEU', 'DEU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'DJI', 'DJI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'DMA', 'DMA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'DNK', 'DNK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'DOM', 'DOM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'DZA', 'DZA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ECU', 'ECU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'EGY', 'EGY', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ERI', 'ERI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ESH', 'ESH', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ESP', 'ESP', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'EST', 'EST', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ETH', 'ETH', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'FIN', 'FIN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'FJI', 'FJI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'FLK', 'FLK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'FRA', 'FRA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'FRO', 'FRO', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'FSM', 'FSM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GAB', 'GAB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GBR', 'GBR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GEO', 'GEO', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GGY', 'GGY', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GHA', 'GHA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GIB', 'GIB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GIN', 'GIN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GLP', 'GLP', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GMB', 'GMB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GNB', 'GNB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GNQ', 'GNQ', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GRC', 'GRC', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GRD', 'GRD', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GRL', 'GRL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GTM', 'GTM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GUF', 'GUF', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GUM', 'GUM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'GUY', 'GUY', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'HKG', 'HKG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'HMD', 'HMD', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'HND', 'HND', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'HRV', 'HRV', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'HTI', 'HTI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'HUN', 'HUN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'IDN', 'IDN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'IMN', 'IMN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'IND', 'IND', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'IOT', 'IOT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'IRL', 'IRL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'IRN', 'IRN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'IRQ', 'IRQ', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ISL', 'ISL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ISR', 'ISR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ITA', 'ITA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'JAM', 'JAM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'JEY', 'JEY', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'JOR', 'JOR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'JPN', 'JPN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'KAZ', 'KAZ', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'KEN', 'KEN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'KGZ', 'KGZ', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'KHM', 'KHM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'KIR', 'KIR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'KNA', 'KNA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'KOR', 'KOR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'KWT', 'KWT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LAO', 'LAO', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LBN', 'LBN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LBR', 'LBR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LBY', 'LBY', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LCA', 'LCA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LIE', 'LIE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LKA', 'LKA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LSO', 'LSO', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LTU', 'LTU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LUX', 'LUX', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'LVA', 'LVA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MAC', 'MAC', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MAF', 'MAF', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MAR', 'MAR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MCO', 'MCO', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MDA', 'MDA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MDG', 'MDG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MDV', 'MDV', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MEX', 'MEX', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MHL', 'MHL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MKD', 'MKD', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MLI', 'MLI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MLT', 'MLT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MMR', 'MMR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MNE', 'MNE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MNG', 'MNG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MNP', 'MNP', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MOZ', 'MOZ', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MRT', 'MRT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MSR', 'MSR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MTQ', 'MTQ', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MUS', 'MUS', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MWI', 'MWI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MYS', 'MYS', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'MYT', 'MYT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NAM', 'NAM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NCL', 'NCL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NER', 'NER', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NFK', 'NFK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NGA', 'NGA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NIC', 'NIC', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NIU', 'NIU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NLD', 'NLD', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NOR', 'NOR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NPL', 'NPL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NRU', 'NRU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'NZL', 'NZL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'OMN', 'OMN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PAK', 'PAK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PAN', 'PAN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PCN', 'PCN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PER', 'PER', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PHL', 'PHL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PLW', 'PLW', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PNG', 'PNG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'POL', 'POL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PRI', 'PRI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PRK', 'PRK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PRT', 'PRT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PRY', 'PRY', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PSE', 'PSE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'PYF', 'PYF', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'QAT', 'QAT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'REU', 'REU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ROU', 'ROU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'RUS', 'RUS', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'RWA', 'RWA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SAU', 'SAU', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SCG', 'SCG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SDN', 'SDN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SEN', 'SEN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SGP', 'SGP', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SGS', 'SGS', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SHN', 'SHN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SJM', 'SJM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SLB', 'SLB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SLE', 'SLE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SLV', 'SLV', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SMR', 'SMR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SOM', 'SOM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SPM', 'SPM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SRB', 'SRB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SSD', 'SSD', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'STP', 'STP', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SUN', 'SUN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SUR', 'SUR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SVK', 'SVK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SVN', 'SVN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SWE', 'SWE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SWZ', 'SWZ', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SXM', 'SXM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SYC', 'SYC', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'SYR', 'SYR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TCA', 'TCA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TCD', 'TCD', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TGO', 'TGO', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'THA', 'THA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TJK', 'TJK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TKL', 'TKL', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TKM', 'TKM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TLS', 'TLS', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TON', 'TON', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TTO', 'TTO', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TUN', 'TUN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TUR', 'TUR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TUV', 'TUV', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TWN', 'TWN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'TZA', 'TZA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'UGA', 'UGA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'UKR', 'UKR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'UMI', 'UMI', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'URY', 'URY', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'USA', 'USA', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'UZB', 'UZB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'VAT', 'VAT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'VCT', 'VCT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'VEN', 'VEN', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'VGB', 'VGB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'VIR', 'VIR', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'VNM', 'VNM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'VUT', 'VUT', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'WAK', 'WAK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'WLF', 'WLF', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'WSM', 'WSM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'XXK', 'XXK', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'XXX', 'XXX', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'YEM', 'YEM', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'YUG', 'YUG', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ZAF', 'ZAF', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ZMB', 'ZMB', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', 'ZWE', 'ZWE', null);
INSERT INTO KODELISTE (ID, KODEVERK, KODE, OFFISIELL_KODE, BESKRIVELSE)
VALUES (nextval('seq_kodeliste'), 'LANDKODER', '-', null, 'Ikke definert');
