name: Bygg og deploy

on:
  push:
    branches:
      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: fp_unit
          POSTGRES_DB: fp_unit
          POSTGRES_PASSWORD: fp_unit
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: create docker tag
        env:
          DOCKER_IMAGE: docker.pkg.github.com/${{ github.repository }}/fp-abakus
        run: |
          echo $DOCKER_IMAGE > .docker_image
          echo $(echo $GITHUB_SHA | cut -c1-7) > .docker_tag
      - name: Build
        shell: bash
        run: |
          echo "Building artifacts $(cat .docker_tag)"
          mvn package --settings ./.m2/settings.xml  --batch-mode --file pom.xml -Dchangelist= -Dsha1=-$(cat .docker_tag)
          echo "Building docker image
          docker build --pull -t $(cat .docker_image):$(cat .docker_tag) .
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DATASOURCE_HOST: localhost
          DATASOURCE_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
      - name: push docker image
        run: |
          echo "${ACCESS_TOKEN}" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          docker push $(cat .docker_image):$(cat .docker_tag)
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

