name: Promote
on:
    repository_dispatch:
        types: [promote-command]

jobs:
    promote:
        name: Deploy
        uses: navikt/fp-gha-workflows/.github/workflows/promote-abakus.yml@main
        with:
            issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
            cluster: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}
            resource: ${{ github.event.client_payload.slash_command.args.unnamed.arg1 }}-teamforeldrepenger.yaml
        secrets: inherit
